# Generated by Django 6.0.5 on 2026-06-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='offer',
            field=models.ManyToManyField(related_name='ofr', to='one.hotel'),
        ),
    ]
